apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer
  template:
    metadata:
      labels:
        app: transfer
    spec:
      containers:
        - name: transfer
          image: mcat1980/bank-transfer:1.0
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: transfer
            - secretRef:
                name: transfer
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30 # 120s runs keycloak
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30 # 120s runs keycloak
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 30
  strategy: { }
status: { }