apiVersion: v1
kind: Secret
metadata:
  name: transfer
stringData:
  KEYCLOAK_CLIENT_ID: bank_transfer
  KEYCLOAK_CLIENT_SECRET: TBdc8HtAio8f0SXlvHPWS6Cbbz5i6yEf

  DATASOURCE_USERNAME: postgres
  DATASOURCE_PASSWORD: Inushing1980