apiVersion: v1
kind: Service
metadata:
  name: {{ include "exchange.fullname" . }}
  labels:
    {{- include "exchange.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "exchange.selectorLabels" . | nindent 4 }}
status: {}