apiVersion: v1
kind: Secret
metadata:
  name: account
stringData:
  KEYCLOAK_CLIENT_ID: bank_accounts
  KEYCLOAK_CLIENT_SECRET: EF3owQYOVaDIDnBr14jkSt3kuResW6x0
  DATASOURCE_USERNAME: postgres
  DATASOURCE_PASSWORD: Inushing1980