apiVersion: v1
kind: Service
metadata:
  name: notifications
spec:
  selector:
    app: notifications
  ports:
    - name: 8080-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
status: {}