server.port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  sql.init:
    mode: always
    schema-locations: classpath:schema.sql

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/bankapp
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/bankapp
        registration:
          bank_transfer:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            clientAuthenticationMethod: client_secret_post

management.endpoints.web.exposure.include: info, health

logging:
  pattern.file: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: ${LOG_LEVEL:DEBUG}
    org.zalando.logbook: ${LOG_LEVEL:DEBUG}

application:
  service:
    urls:
      account: ${SERVICE_URL_ACCOUNT}
      exchange: ${SERVICE_URL_EXCHANGE}
      blocker: ${SERVICE_URL_BLOCKER}
      notifications: ${SERVICE_URL_NOTIFICATIONS}
      transfer: ${SERVICE_URL_TRANSFER}
