apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exchange-generator.fullname" . }}
  labels:
    {{- include "exchange-generator.labels" . | nindent 4 }}
stringData:
  KEYCLOAK_CLIENT_ID: {{ .Values.KEYCLOAK_CLIENT_ID }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.KEYCLOAK_CLIENT_SECRET }}
