apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
          {{ range .Values.arguments }}
          - {{ . }}
          {{ end }}
          envFrom:
            - secretRef:
                name: {{ include "keycloak.fullname" . }}
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - mountPath: /opt/keycloak/data/import
              name: keycloak-data
      volumes:
        - name: keycloak-data
          configMap:
            optional: false
            name: {{ include "keycloak.fullname" . }}
