apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: {{ .Values.KC_BOOTSTRAP_ADMIN_USERNAME }}
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.KC_BOOTSTRAP_ADMIN_PASSWORD }}