apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange-generator
  template:
    metadata:
      labels:
        app: exchange-generator
    spec:
      containers:
        - name: exchange-generator
          image: mcat1980/bank-exchange-generator:1.0
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: exchange-generator
          env:
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: exchange-generator
                  key: KEYCLOAK_CLIENT_ID
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: exchange-generator
                  key: KEYCLOAK_CLIENT_SECRET
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30 # 120s runs keycloak
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30 # 120s runs keycloak
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 30
  strategy: { }
status: { }