apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cash-db
spec:
  serviceName: cash-db
  replicas: 1
  selector:
    matchLabels:
      app: cash-db
  template:
    metadata:
      labels:
        app: cash-db
    spec:
      containers:
        - name: cash-db
          image: postgres:17.5
          env:
            - name: POSTGRES_DB
              value: data
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cash
                  key: DATASOURCE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cash
                  key: DATASOURCE_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgres/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: cash-db
spec:
  clusterIP: None
  selector:
    app: cash-db
  ports:
    - name: 5432-5432
      port: 5432
      targetPort: 5432
      protocol: TCP