apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transfer.fullname" . }}
  labels:
    {{- include "transfer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "transfer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "transfer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ include "transfer.fullname" . }}
            - secretRef:
                name: {{ include "transfer.fullname" . }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: {{ .Values.INITIAL_DELAY_SEC }}
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: {{ .Values.INITIAL_DELAY_SEC }}
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 30
  strategy: { }
status: { }