apiVersion: v1
kind: Service
metadata:
  name: {{ include "notifications.fullname" . }}
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "notifications.selectorLabels" . | nindent 4 }}
status: {}