apiVersion: v1
kind: Service
metadata:
  name: {{ include "cash.fullname" . }}
  labels:
    {{- include "cash.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "cash.selectorLabels" . | nindent 4 }}
status: {}